[ 2024-11-25 17:15:12,742 ] 22 root - INFO - Data Ingesion has been started
[ 2024-11-25 17:15:12,743 ] 24 root - INFO - Data reading using Pandas from local file system
[ 2024-11-25 17:15:12,760 ] 26 root - INFO - Data Reading has been completed
[ 2024-11-25 17:15:12,787 ] 30 root - INFO - Raw data has been stored
[ 2024-11-25 17:15:12,789 ] 33 root - INFO - Raw data has been splitted into Train and Test set
[ 2024-11-25 17:15:12,816 ] 38 root - INFO - Data Ingestion has been completed!
[ 2024-11-25 17:15:12,816 ] 103 root - INFO - Created feature store configuration at /home/bs01224/Desktop/study/mlops/module 3/task/behaviour-prediction/feature_repo/feature_store.yaml
[ 2024-11-25 17:15:12,817 ] 107 root - INFO - Configuration file content:

project: behaviour_prediction
provider: local
registry: data/registry.db
online_store:
    type: sqlite
offline_store:
    type: file
entity_key_serialization_version: 2

[ 2024-11-25 17:15:13,195 ] 111 root - INFO - Feature store initialized successfully
[ 2024-11-25 17:15:13,214 ] 176 root - INFO - Read train and test data completed
[ 2024-11-25 17:15:13,214 ] 177 root - INFO - Obtaining preprocessing object
[ 2024-11-25 17:15:13,229 ] 210 root - INFO - Applying preprocessing object on training and testing datasets.
[ 2024-11-25 17:15:13,269 ] 216 root - INFO - Starting feature store operations
[ 2024-11-25 17:15:13,284 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:13,287 ] 409 root - WARNING - Cannot use sqlite_vec for vector search
[ 2024-11-25 17:15:13,289 ] 293 root - INFO - Applied entity and feature view for train
[ 2024-11-25 17:15:13,289 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:13,292 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:13,292 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:15,134 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:15,686 ] 300 root - INFO - Materialized features successfully
[ 2024-11-25 17:15:15,698 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:15,702 ] 293 root - INFO - Applied entity and feature view for test
[ 2024-11-25 17:15:15,702 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:15,705 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:15,705 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:17,465 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-25 17:15:18,039 ] 300 root - INFO - Materialized features successfully
[ 2024-11-25 17:15:18,039 ] 222 root - INFO - Pushed training & testing data to feature store
[ 2024-11-25 17:15:18,203 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x722d56493250>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Churn_Prediction_Pipeline
[ 2024-11-25 17:15:22,593 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x722d56493460>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Churn_Prediction_Pipeline
[ 2024-11-25 17:15:30,771 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x722d56493610>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Churn_Prediction_Pipeline
[ 2024-11-25 17:15:47,343 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x722d564937c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Churn_Prediction_Pipeline
[ 2024-11-25 17:16:19,969 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x722d56493970>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Churn_Prediction_Pipeline
